HDC_INCLUDE=-I. $(shell pkg-config fhdc --cflags)
HDC_LIBS=$(shell pkg-config fhdc --libs)
HDC_CFLAGS=-fPIC -g -ffree-line-length-none -pedantic -fbacktrace -std=f2008

all: {%- if func.do_compile is sameas true %} {{ func.soname }} {%- endif %} {{ func.module }}_bind.so

{% if func.do_compile is sameas true %}
{{ func.soname }}: {{ func.module }}.f90
	gfortran  $(HDC_CFLAGS) -shared -o {{ func.soname }} {{ func.source_file }} $(HDC_INCLUDE) $(HDC_LIBS)
{% endif %}

{{ func.module }}_bind.so: {{ func.module }}_bind.f90
	gfortran  $(HDC_CFLAGS) -shared -o {{ func.module }}_bind.so $< -I. -L. -J. -L{{ func.soname }} $(HDC_INCLUDE) $(HDC_LIBS)
