HDC_INCLUDE=-I. $(shell pkg-config fhdc --cflags)
HDC_LIBS=$(shell pkg-config fhdc --libs)
HDC_CFLAGS=-fPIC -g -ffree-line-length-none -pedantic -fbacktrace -std=f2008

all: lib{{ func.module }}.so lib{{ func.module }}_bind.so

lib{{ func.module }}.so: {{ func.module }}.f90
	gfortran  $(HDC_CFLAGS) -shared \
	    -o {{ func.module }}.so {{ func.module }}.f90 \
		$(HDC_INCLUDE) $(HDC_LIBS)

lib{{ func.module }}_bind.so: {{ func.module }}_bind.f90
	gfortran  $(HDC_CFLAGS) -shared \
	    -o {{ func.module }}_bind.so $< -I. -L. -J. -L{{ func.module }}.so \
	    $(HDC_INCLUDE) $(HDC_LIBS)
