/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_libhdc_HDC_HDCException */

#ifndef _Included_dev_libhdc_HDC_HDCException
#define _Included_dev_libhdc_HDC_HDCException
#ifdef __cplusplus
extern "C" {
#endif
#undef dev_libhdc_HDC_HDCException_serialVersionUID
#define dev_libhdc_HDC_HDCException_serialVersionUID -3042686055658047285LL
#undef dev_libhdc_HDC_HDCException_serialVersionUID
#define dev_libhdc_HDC_HDCException_serialVersionUID -3387516993124229948LL
#undef dev_libhdc_HDC_HDCException_serialVersionUID
#define dev_libhdc_HDC_HDCException_serialVersionUID -7034897190745766939LL
#ifdef __cplusplus
}
#endif
#endif
